version: '3.7'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        ports:
            - ${NGINX_PORT_MAP_HTTP}
            - ${NGINX_PORT_MAP_HTTPS}
        volumes:
            - ./app:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        working_dir: /var/www
        restart: always
    php:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./app:/var/www
        working_dir: /var/www
        restart: always
    postgres:
        build:
            context: ./docker
            dockerfile: postgres.docker
        volumes:
            # For Linux
            # - ./storage/postgres:/var/lib/postgresql/data
            # For Windows
            - postgres:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT_MAP}
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: always
# For Windows
volumes:
    postgres:
        external: true